### ISSUE TITLE
type coverage not being updated.

### ISSUE THREAD

**Issue by azjezz** [psalm/shepherd#15]
I have noticed recently that type coverage has stopped being updated for one of my projects ( https://github.com/azjezz/psl ), I'm not sure if this is an issue on my side, but the CI script has always been the same ( see: https://github.com/azjezz/psl/blob/develop/.travis.yml#L33 / https://github.com/azjezz/psl/blob/develop/composer.json#L42 ).

The latest CI build ran just a few seconds ago, but the latest update according to shepherd.dev is 4 months ago ( https://shepherd.dev/github/azjezz/psl ).

The only thing I can think of that has changed since then is the default branch name from `master` to `develop`

current type coverage: 100% ( 100.084 actually 😆 )
type coverage in shepherd: 91%

**Comment by muglug** [comment]
> The only thing I can think of that has changed since then is the default branch name from master to develop

That’ll be it. How can shepherd figure out what the default branch is?

**Comment by azjezz** [comment]
I think either using GitHub API or congiured in psalm.xml?

**Comment by azjezz** [comment]
GitHub API: https://docs.github.com/en/rest/reference/repos#get-a-repository ( default_branch property in the response )

**Comment by azjezz** [comment]
awesome!
![image](https://user-images.githubusercontent.com/29315886/88466282-a080e300-cec2-11ea-9b47-d0776a10f49d.png)

**Comment by ramsey** [comment]
I've run into an issue that might be related to this. I changed the default branch on [ramsey/collection](https://github.com/ramsey/collection) to `2.0.x`, and my GitHub Actions are showing:

```
🐑 results sent to shepherd.dev 🐑
```

However, I'm not seeing any results listed at https://shepherd.dev/github/ramsey/collection

Could this be a GitHub API caching issue, or something else?

**Comment by markuspoerschke** [comment]
I just tried changing the default branch myself on one of my projects and it works fine.

@ramsey Are you talking about this commit https://github.com/ramsey/collection/commit/8e1a03bc0f9be5ed437c4f7c62a8da8815e36e49 ? To me it looks like the type coverage is now displayed correctly.
