### ISSUE TITLE
Support shields.io

### ISSUE THREAD

**Issue by staabm** [psalm/shepherd#5]
Does shephard.dev support a json endpoint (or something similar) to support shields.io badges?
https://shields.io/

We use this badges, which are more customizable/beautiful. Would be great all of our badges would have the same visual appearance

See our projects readme as an example
https://github.com/redaxo/redaxo/blob/master/README.md

**Comment by muglug** [comment]
Behold: ![badge](https://img.shields.io/endpoint?style=for-the-badge&url=https%3A%2F%2Fshepherd.dev%2Fgithub%2Fredaxo%2Fredaxo%2Fcoverage)

**Comment by staabm** [comment]
Thank you ❤️
