### ISSUE TITLE
Badge of new project is not recognized 

### ISSUE THREAD

**Issue by staabm** [psalm/shepherd#6]
A few hours ago we added `shepherd` but the badge is still rendered as „unknown“, see https://camo.githubusercontent.com/551ab204c7b0a8690d86e223d9552a75174ad2ff/68747470733a2f2f73686570686572642e6465762f6769746875622f72656461786f2f72656461786f2f636f7665726167652e737667

The github action reports that the coverage data was uploaded successfully 

https://github.com/redaxo/redaxo/pull/3098/files

**Comment by muglug** [comment]
It'll appear once merged into master!

**Comment by staabm** [comment]
You are right. Works after merge, thx
